### ISSUE TITLE
top_values broken

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/linelist#89] opened 2019-09-23 07:16 UTC
At 58ed4c745ef6ee4799e0912a5704a1176c084db2 I get:

```
x <- c('a', 'b', 'a', 'b', 'c')
top_values(x, 1)
```
returns
```
[1] "a" "b" "a" "b" "c"
```

**Comment by zkamvar** [comment] 2019-09-23 08:47
closing this in favor of #88 for more context and less ambiguous title.

**Comment by zkamvar** [comment] 2019-09-23 15:04
again, closing this in favor of #88, because the problem is better defined there.

**Closed as completed by zkamvar** 2019-09-23 15:04 UTC
Labels: bug, high priority
